#!/bin/bash

# Copyright (c) 2009-2015, NVIDIA CORPORATION.  All rights reserved.
# See /etc/LICENSE file for details.

set -e

die()
{
    echo "$@"
    exit 1
}

[ $# -gt 0 ] || die "Usage: `basename $0` <DEVICE1> [DEVICE2 [...]]"

# Check required tools
[ -x /sbin/mkfs.vfat   ] || die "/sbin/mkfs.vfat not found"
[ -x /sbin/fdisk       ] || die "/sbin/fdisk not found"
[ -x /usr/bin/syslinux ] || die "/usr/bin/syslinux not found"
[ -f /usr/share/syslinux/mbr.bin ] || die "mbr.bin not found"

# Find TinyLinux directory
TINY="`tinydir`"
[ -d "$TINY" ] || die "TinyLinux directory not found"

IBLK=1
while [ $IBLK -le $# ]; do
    BLKDEV=`eval "echo "'$'"$IBLK"`
    BLKDEV="${BLKDEV#/dev/}"
    [ -e "/sys/class/block/$BLKDEV" ] || die "/dev/$BLKDEV device does not exist!"
    cut -f 1 -d ' ' < /proc/mounts | grep -q "$BLKDEV" && \
        die "/dev/$BLKDEV device is already mounted!"
    IBLK=$(($IBLK+1))
done

UMOUNT_DEV1=""

umount_on_exit()
{
    sync
    [ -z $UMOUNT_DEV1 ] || umount "$UMOUNT_DEV1" || echo "Umount failed - device $UMOUNT_DEV1 may be still mounted!"
}

trap umount_on_exit EXIT

install_tiny()
{
    local BLKDEV
    local DEV

    BLKDEV="$1"

    # Install master boot record and existing clear partition table
    dd if=/dev/zero of="$BLKDEV" bs=512 count=1
    cat /usr/share/syslinux/mbr.bin > "$BLKDEV"
    sync

    # Create partitions
    echo -en "np11 a1pw" | sed "s/./&\n/g" | /sbin/fdisk "$BLKDEV"
    sync
    find /sys/devices/ -name uevent -exec sh -c "echo add > '{}'" \;
    sleep 4
    grep "^$BLKDEV" < /proc/mounts | cut -f 1 -d ' ' | while read DEV; do
        umount "$DEV"
    done
    /sbin/mkfs.vfat -n "TinyLinux" "${BLKDEV}1"
    sync

    # Install TinyLinux
    local INSTALLDIR
    INSTALLDIR="`mktemp -d -t`"
    mount "${BLKDEV}1" "$INSTALLDIR"
    UMOUNT_DEV1="${BLKDEV}1"
    mkdir -p "$INSTALLDIR/home"
    cp -r "$TINY" "$INSTALLDIR/tiny"
    [ -f /mnt/nv/README       ] && cp /mnt/nv/README       "$INSTALLDIR"
    [ -f /mnt/nv/syslinux.exe ] && cp /mnt/nv/syslinux.exe "$INSTALLDIR"
    [ -d /mnt/nv/EFI          ] && cp -r /mnt/nv/EFI       "$INSTALLDIR"

    # Make it bootable
    mkdir -p "$INSTALLDIR/syslinux"
    echo "default /tiny/kernel initrd=/tiny/initrd" > "$INSTALLDIR"/syslinux/syslinux.cfg
    /usr/bin/syslinux --install "${BLKDEV}1"
    UMOUNT_DEV1=""
    sync
    umount "${BLKDEV}1"
    rmdir "$INSTALLDIR"
}

install_wrap()
{
    local STATUS
    echo "Installing TinyLinux on $1"
    install_tiny "$1" 2<&1 | sed "s/^/${1//\//\\/}: /" | tee -a "/var/log/install"
    STATUS=${PIPESTATUS[0]}
    [ $STATUS -eq 0 ] || exit $STATUS
    echo "TinyLinux installed successfuly on $1"
}

while [ $# -gt 0 ]; do
    install_wrap "/dev/${1#/dev/}" &
    shift
done

wait
