#!/bin/sh

# Copyright (c) 2009-2015, NVIDIA CORPORATION.  All rights reserved.
# See /etc/LICENSE file for details.

# Rename old mods.log
if [ -f "mods.log" ]; then
    DATE=`stat -c %y mods.log | sed "s/[-:]/ /g ; s/\..*//" | cut -d ' ' -f 2,3,4,5 | tr -d ' '`
    NEWNAME="$DATE.log"
    [ -f "$NEWNAME" ] && DATE=`mktemp "./$NEWNAME.XXXXXX"`
    echo "Renaming old mods.log to $NEWNAME"
    mv "mods.log" "$NEWNAME"
fi

# Run with gdbserver if requested
GDB=""
if [ "$1" = "gdb" ]; then
    GDB="gdbserver h:1234"
    shift
fi

# Kick off MODS
exec $GDB "$MODS_RUNSPACE/mods" "$@"
