#!/usr/bin/sh

# Copyright (c) 2009-2023, NVIDIA CORPORATION.  All rights reserved.
# See /etc/LICENSE file for details.

emit()
{
    local LEVEL=$1
    shift
    logger -p 24.$LEVEL -t mdev.sd_mounts "$@"
}

log()
{
    emit 6 "$@"
}

error()
{
    emit 3 "$@"
}

log "$ACTION $SUBSYSTEM $MDEV $DEVTYPE"

shouldmount()
{
    # Detect partitions
    if [ "$2" = "disk" ]; then
        dd if="/dev/$1" bs=512 count=1 2>/dev/null | grep -q FAT || return 1
    elif [ "$2" != "partition" ]; then
        return 1
    fi

    # Skip boot partition
    if [ -x /usr/bin/tinydir ] && [ ! -f "`/usr/bin/tinydir`/kernel" ]; then
        if grep -q "2 /mnt/nv " /proc/mounts; then
            local INSTALL
            INSTALL=`grep " /mnt/nv " /proc/mounts | awk '{print $1}'`
            INSTALL=${INSTALL#/dev/}
            [ "$1" = "${INSTALL/2/1}" ] && return 2
        fi
    fi

    # Skip if it's already in /etc/fstab
    grep -q "^/dev/${1}\>" /etc/fstab && return 3

    return 0
}

if [ "$ACTION" = "remove" ]; then
    if mountpoint -q "/media/$MDEV"; then
        log "unmount /media/$MDEV"
        umount "/media/$MDEV" 2>&1 | error
        rmdir "/media/$MDEV"
    fi
elif [ "$ACTION" = "add" ]; then
    if ! grep -q "^/dev/$MDEV\>" /proc/mounts; then
        shouldmount "$MDEV" "$DEVTYPE"
        case "$?" in
        0)  log "mount /media/$MDEV"
            mkdir -p "/media/$MDEV"
            mount "/dev/$MDEV" "/media/$MDEV" 2>&1 | error || (
                rmdir "/media/$MDEV"
                error "mount /media/$MDEV failed"
            )
            ;;
        2)  log "skipping boot partition /dev/$MDEV"
            ;;
        3)  log "skipping /dev/$MDEV from /etc/fstab"
            ;;
        *)  log "ignored /dev/$MDEV"
            ;;
        esac
    else
        log "skipping /dev/$MDEV, already mounted"
    fi
fi
