export PATH="/usr/bin"
export EDITOR="/usr/bin/nano"
export PS1="\n\[\033[1;32m\][\t] \[\033[1;33m\]\w\[\033[0m\]\n\\$ "
export LC_ALL="en_US.utf8"
export TZ=UTC
export PYTHONUSERBASE="`tinydir`/python"

[ -d "`modsoutputdir`" ] && cd "`modsoutputdir`"
